	def	nameconv(name, league)
		case '*'+name+'*'
		when '*air force*'
			return 'Air Force Falcons'
		when 'alabama'
			return 'Alabama Crimson Tide'
		when '*akron*'
			return 'Akron Zips'
		when '*arizona state*'
			return 'Arizona State Sun Devils'
		when '*arizona u*'
			return 'Arizona Wildcats'
		when '*arkansas state*'
			return 'arkansas State  Indians'
		when '*arkansas*'
			return "Arkansas Razorback Hogs"
		when '*army*'
			return 'Army  Black Knights'
		when '*auburn*'
			return 'Auburn Tigers'
		when '*ball state*'
			return 'Ball State Cardinals'
		when '*baylor*'
			return "Baylor Bears"
		when '*boise state*'
			return 'Boise State Broncos'
		when '*boston college*'
			return 'Boston College Eagles'
		when '*bowling green*'
			return 'Bowling Green Falcons'
		when '*buffalo*'
			return 'Buffalo Bills'
		when '*byu*'
			return 'BYU Cougars'
		when '*california*'
			return 'California Golden Bears'
      		when '*central florida*'
			return 'Central Florida Golden Knights'
		when '*central michigan*'
			return 'Central Michigan Chippewas'
		when '*cincinnati u*'
			return 'Cincinnati Bearcats'
		when '*clemson*'
			return 'Clemson Tigers'
		when '*colorado state*'
			return 'Colorado State Rams'
		when '*colorado*'
			return 'Colorado Buffaloes'
		when '*depaul*'
			return 'DePaul Blue Demons'
		when '*duke*'
			return 'Duke Blue Devils'
		when '*east carolina*'
			return 'East Carolina Pirates'
		when '*eastern michigan*'
			return 'Eastern Michigan Eagles'
		when '*florida atlantic*'
			return 'Florida Atlantic Owls'
		when '*florida international*'
			return 'Florida International Golden Panthers'
		when '*florida state*'
			return 'Florida State Seminoles'
		when '*florida*'
			return "Florida Gators #{(league == 4 ? 'with Tim Tebow' : '')} "
		when '*fresno state*'
			return 'Fresno State Bulldogs'
		when '*georgetown*'
			return 'Georgetown Hoyas'
		when '*georgia tech*'
			return 'Georgia Tech Yellow Jackets'
		when '*georgia*'
			return 'Georgia Bulldogs'
		when '*hawaii*'
			return "Hawaii Warriors"
		when '*houston u*'
			return 'Houston Cougars'
		when '*idaho*'
			return 'Idaho Vandals'
		when '*illinois fighting*'
			return 'Illinois Fighting Illini'
		when '*indiana*'
			return 'Indiana Hoosiers'
		when '*iowa*'
			return 'Iowa Hawkeyes'
		when '*iowa state*'
			return 'Iowa State Cyclones'
		when '*kansas state*'
			return 'Kansas State Wildcats'
		when '*kansas*'
			return 'Kansas Jayhawks'
		when '*kent state*'
			return 'Kent State Golden Flashes'
		when '*kentucky*'
			return 'Kentucky Wildcats'
		when '*louisiana tech*'
			return 'Louisiana Tech Bulldogs'
		when '*louisville*'
			return 'Louisville Cardinals'
		when '*lsu*'
			return 'LSU Tigers'
		when '*marquette*'
			return 'Marquette Golden Eagles'
		when '*marshall*'
			return 'Marshall Thundering Herd'
		when '*maryland*'
			return 'Maryland Terrapin'
		when '*memphis*'
			return 'Memphis Tigers'
		when '*miami*'
			return 'Miami Hurricanes'
		when '*miami ohio*'       
			return 'Miami Red Hawks'
		when '*michigan state*'
			return 'Michigan State Spartans'
		when '*michigan*'
			return 'Michigan Wolverines'
		when '*middle tennessee state*'
			return 'Middle Tennessee State Blue Raiders'
		when '*minnesota golden*'
			return 'Minnesota Golden Gophers'
		when '*mississipi*'
			return 'Ole Miss Rebels'
		when '*mississippi state*'
			return 'Mississippi State Bulldogs'
		when '*missouri*'
			return 'Missouri Tigers'
		when '*nevada*'
			return "Nevada Wolf Pack"
		when '*navy*'
			return "Navy Midshipmen"
		when '*nc state*'
			return 'NC State Wolfpack'
		when '*nebraska*'
			return "Nebraska Cornhuskers"
		when '*nevada wolf pack*'
			return 'Nevada Wolf Pack'
		when '*new mexico*'
			return 'New Mexico Lobos'
		when '*new mexico state aggies*'
			return 'New Mexico State Aggies'
		when '*north carolina*'
			return 'North Carolina Tar Heels'
		when '*north texas*'
			return 'North Texas Mean Green'
		when '*northern illinois*'
			return 'Northern Illinois Huskies'
		when '*northwestern*'
			return 'Northwestern Wildcats'
		when '*notre dame*'
			return 'Notre Dame Fighting Irish'
		when '*ohio*'
			return 'Ohio Bobcats'
		when '*ohio state*'
			return 'Ohio State Buckeyes'
		when '*oklahoma state*'
			return 'Oklahoma State Cowboys'
		when '*oklahoma*'
			return "Oklahoma Sooners"
		when '*oregon*'
			return 'Oregon Ducks'
		when '*oregon state*'
			return 'Oregon State Beavers'
		when '*penn state*'
			return 'Penn State Nittany Lions'
		when '*pittsburgh*'
			return 'Pittsburgh Panthers'
      		when '*princeton*'
			return 'Princeton Tigers'
		when '*providence*'
			return 'Providence Friars'
		when '*purdue*'
			return "Purdue Boilermakers"
		when '*rice*'
			return 'Rice Owls'
		when '*rutgers*'
			return 'Rutgers Scarlet Knights'
		when '*san diego state*'
			return 'San Diego State Aztecs'
		when '*san jose state*'
			return 'San Jose State Spartans'
		when '*seton hall*'
			return 'Seton Hall Pirates'
		when '*smu*'
			return 'SMU Mustangs'
		when '*south carolina*'
			return 'South Carolina Gamecocks'
		when '*so mississippi*'
			return 'Southern Miss Golden Eagles'
		when '*st. johns*'
			return 'St. Johns Red Storm'
		when '*stanford*'
			return 'Stanford Cardinals'
		when '*syracuse*'
			return 'Syracuse Orangemen'
		when '*tcu*'
			return 'TCU Horned Frogs'
		when '*temple*'
			return "Temple Owls"
		when '*tennessee u*'
			return 'Tennessee Volunteers'
		when '*texas am*'
			return "Texas A&M Aggies"
		when '*texas tech*'
			return "Texas Tech Red Raiders #{(league == 4 ? 'with Coach Leech' : '')}"
		when '*toledo*'
			return 'Toledo Rockets'
		when '*troy*'
			return 'Troy Trojans'
		when '*tulane*'
			return 'Tulane Green Wave'
		when '*tulsa*'
			return 'Tulsa Golden Hurricane'
		when '*uab*'
			return 'UAB Blazers'
		when '*ucf*'
			return 'UCF Golden Knights'
		when '*ucla*'
			return "UCLA Bruins"
		when '*uconn*'
			return 'UConn Huskies'
		when '*ul - lafayette*'
			return 'UL Lafayette Ragin Cajuns'
		when '*ul monroe*'                                                                                                                          
			return 'UL Monroe Indians'
		when '*unc*'
			return 'North Carolina Tarheels'
		when '*unlv*'
			return 'UNLV Rebels'
		when '*usc*'
			return "USC Trojans"
		when '*usf*'
			return 'USF Bulls'
		when '*utah state*'
			return 'Utah State Aggies'
		when '*utah*'
			return 'Utah Utes'
		when '*utep*'
			return 'UTEP Miners'
		when '*vanderbilt*'
			return 'Vanderbilt Commodores'
		when '*villanova*'
			return 'Villanova Wildcats'
		when '*virginia*'
			return 'Virginia Cavaliers'
		when '*virginia tech*'
			return 'Virginia Tech Hokies'
		when '*wake forest*'
			return "Wake Forest Demon Deacons"
		when '*washington u*'
			return 'Washington Huskies'
		when '*washington state*'
			return 'Washington State Cougars'
		when '*west virginia*'
			return 'West Virginia Mountaineers'
		when '*western michigan*'
			return 'Western Michigan Broncos'
		when '*wisconsin*'
			return 'Wisconsin Badgers'
		when '*wyoming*'
			return 'Wyoming Cowboys'
		when '*xavier*'
			return 'Xavier X-Men'
		else
         return name
	end # case
end # def	nameconv

